#!/bin/bash

set -o pipefail
export LANG=C.UTF-8

export API=${API:-https://api.openai.com/v1/responses}
export KEY=${KEY:-$(< ~/.config/secrets/openai)}
export MODEL=${MODEL:-gpt-4.1}

if [[ -t 0 ]] && [[ $# -eq 0 ]] || [[ $1 == -* ]]; then
  echo "Usage: ${0##*/} [PROMPT] < INPUT" 2>&1
  exit 64
elif [[ -t 0 ]]; then
  exec < /dev/null
fi

exec 3<<EOF
{
  "model": env.MODEL,
  "store": false,
  "stream": true,
  "tools": [ { type: "web_search_preview" } ],
  "input": . | rtrimstr("\\n")
} | if .input == "" then
      .input = env.PROMPT
    elif env.PROMPT != "" then
      .instructions = env.PROMPT
    end
EOF

exec 4<<EOF
Authorization: Bearer $KEY
Content-Type: application/json
EOF

exec 5<<EOF
fromjson?
  | .delta
  | gsub("[‘’]"; "'")?
  | gsub("[“”]"; "\\"")?
  | gsub("…"; "...")?
  | gsub(" ?— ?"; " - ")?
EOF

PROMPT=$* jq -f /dev/fd/3 -s -R \
  | curl -d @- -f -m 30 -s -H @/dev/fd/4 -N -S "$API" \
  | sed -n -u 's/^data:\s*//p' \
  | jq -e -f /dev/fd/5 -j -R --unbuffered \
  | fold -s -w 76
set $? ${PIPESTATUS[@]}

if [[ $5 -ne 4 ]]; then
  printf '\n'
fi

if [[ $3 -eq 6 ]] || [[ $3 -eq 7 ]]; then
  echo "Failed to connect to host"
elif [[ $3 -eq 28 ]]; then
  echo "Content generation timed out"
elif [[ $3 -ne 0 ]]; then
  echo "Content generation failed: $3"
elif [[ $5 -ne 0 ]]; then
  echo "Invalid response from model"
fi >&2

exit $(($1 != 0))
