#!/bin/bash

set -o pipefail
export LANG=C.UTF-8

export API=${API:-https://api.openai.com/v1/chat/completions}
export KEY=${KEY:-$(< ~/.config/secrets/openai)}
export MODEL=${MODEL:-gpt-4o}

if [[ -t 0 ]] && [[ $# -eq 0 ]] || [[ $1 == -* ]]; then
  echo "Usage: ${0##*/} [PROMPT] < INPUT" 2>&1
  exit 64
elif [[ -t 0 ]]; then
  exec < /dev/null
fi

exec 3<<EOF
{
  "model": env.MODEL,
  "messages": [
    { "role": "system", "content": env.PROMPT },
    { "role": "user", "content": . | rtrimstr("\\n") }
  ],
  "stream": true
} | .messages[] |= select(.content and .content != "")
EOF

exec 4<<EOF
Authorization: Bearer $KEY
Content-Type: application/json
EOF

exec 5<<EOF
fromjson?
  | .choices[0].delta.content?
  | gsub("[‘’]"; "'")?
  | gsub("[“”]"; "\\"")?
  | gsub("…"; "...")?
  | gsub("\\\\s?—\\\\s?"; " - ")?
EOF

PROMPT=$* jq -f /dev/fd/3 -s -R \
  | curl -d @- -f -m 30 -s -H @/dev/fd/4 -N "$API" \
  | sed -n -u 's/^data:\s*//p' \
  | jq -e -f /dev/fd/5 -j -R --unbuffered \
  | fold -s -w 76
set -- $? ${PIPESTATUS[@]}

if [[ $5 -ne 4 ]]; then
  printf '\n'
fi

if [[ $1 -ne 0 ]]; then
  case $3 in
    0)
      echo "Invalid response from model"
      ;;
    6|7)
      echo "Failed to connect to host"
      ;;
    28)
      echo "Content generation timed out"
      ;;
    *)
      echo "Content generation failed: $3"
      ;;
  esac >&2
  exit 1
fi
