#!/bin/bash

set -o pipefail
export LANG=C.UTF-8

export API=${API:-https://api.openai.com/v1/audio/speech}
export KEY=${KEY:-$(< ~/.config/secrets/openai)}
export MODEL=${MODEL:-gpt-4o-mini-tts}
export VOICE=${VOICE:-ash}

if [[ -t 0 ]] && [[ $1 != [^-]* ]] \
    || [[ -t 1 ]] \
    || [[ $1 == -?* ]] \
    || [[ $# -gt 2 ]]; then
  echo "Usage: ${0##*/} [INPUT] [INSTRUCTIONS] >OUTPUT" >&2
  exit 64
elif [[ $1 == [^-]* ]]; then
  exec <<< "$1"
fi

exec 3<<EOF
{
  "input": . | rtrimstr("\\n"),
  "instructions": env.PROMPT,
  "model": env.MODEL,
  "response_format": env.FORMAT,
  "speed": (env.SPEED | tonumber? // null),
  "voice": env.VOICE,
} | .[] |= select(. and . != "")
EOF

exec 4<<EOF
Authorization: Bearer $KEY
Content-Type: application/json
EOF

PROMPT=$2 jq -f /dev/fd/3 -s -R \
  | curl -d @- -f -m 30 -s -H @/dev/fd/4 -S "$API"
set $? ${PIPESTATUS[@]}

if [[ $2 -eq 6 ]] || [[ $2 -eq 7 ]]; then
  echo "Failed to connect to host"
elif [[ $2 -eq 28 ]]; then
  echo "Speech generation timed out"
elif [[ $2 -ne 0 ]]; then
  echo "Speech generation failed: $2"
fi >&2

exit $(($1 != 0))
