#!/bin/bash

set -o pipefail
export LANG=C.UTF-8

export API=${API:-https://api.openai.com/v1/audio/transcriptions}
export KEY=${KEY:-$(< ~/.config/secrets/openai)}
export MODEL=${MODEL:-whisper-1}

if [[ $# -ne 1 ]]; then
  echo "Usage: ${0##*/} AUDIOFILE" >&2
  exit 64
elif [[ ! -f $1 ]]; then
  echo "Audio file not found: $1" >&2
  exit 1
fi

curl -f -m 30 -s -F file="@$1" -F model="$MODEL" -F response_format=text \
     -H @- "$API" <<< "Authorization: Bearer $KEY" \
  | sed -e "y/‘’“”/''\"\"/" -e 's/…/.../g' -e 's/ \?— \?/ - /g' \
  | fmt -s -w 76
set $? ${PIPESTATUS[@]}

if [[ $2 -eq 6 ]] || [[ $2 -eq 7 ]]; then
  echo "Failed to connect to host"
elif [[ $2 -eq 28 ]]; then
  echo "Transcription timed out"
elif [[ $2 -ne 0 ]]; then
  echo "Transcription failed: $2"
fi >&2

exit $(($1 != 0))
